on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      REGION: ${{ vars.REGION }}
      FRONTEND_SERVICE: ${{ vars.FRONTEND_SERVICE_NAME }}
      BACKEND_SERVICE: ${{ vars.BACKEND_SERVICE_NAME }}
      FRONT_REPO: ${{ vars.FRONT_REPO }}
      BACK_REPO: ${{ vars.BACK_REPO }}
      WIF_PROVIDER: ${{ vars.WIF_PROVIDER }}
      WIF_SERVICE_ACCOUNT_EMAIL: ${{ vars.WIF_SERVICE_ACCOUNT_EMAIL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ env.PROJECT_ID }}
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true
          access_token_lifetime: 3600s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          retries: 3
          backoff: 250
          id_token_include_email: false

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build & push frontend
        run: |
          IMAGE_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/$(echo "${{ env.FRONT_REPO }}" | tr -d '\r')/frontend:latest"
          docker build -t "$IMAGE_TAG" ./my-app
          docker push "$IMAGE_TAG"
  
      - name: Build & push backend
        run: |
          IMAGE_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/$(echo "${{ env.BACK_REPO }}" | tr -d '\r')/backend:latest"
          docker build -t "$IMAGE_TAG" ./server
          docker push "$IMAGE_TAG"
          
      - name: Deploy frontend to Cloud Run
        run: |
          gcloud run deploy ${{ env.FRONTEND_SERVICE }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.FRONT_REPO }}/frontend:latest \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --service-account=${{ env.WIF_SERVICE_ACCOUNT_EMAIL }}

      - name: Deploy backend to Cloud Run
        run: |
          gcloud run deploy ${{ env.BACKEND_SERVICE }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.BACK_REPO }}/backend:latest \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --service-account=${{ env.WIF_SERVICE_ACCOUNT_EMAIL }}
