on:
  push:
    branches: [ main ] # or dev, etc.
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      REGION: ${{ vars.REGION }}
      FRONTEND_SERVICE: ${{ vars.FRONTEND_SERVICE_NAME }}
      BACKEND_SERVICE: ${{ vars.BACKEND_SERVICE_NAME }}
      FRONT_REPO: ${{ vars.FRONT_REPO }}
      BACK_REPO: ${{vars.BACK_REPO}}
      WIF_PROVIDER: ${{ vars.WIF_PROVIDER }}
      WIF_SERVICE_ACCOUNT_EMAIL: ${{ vars.WIF_SERVICE_ACCOUNT_EMAIL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SERVICE_ACCOUNT_EMAIL }}
          
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build & push frontend
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$FRONT_REPO/frontend:latest ./my-app
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$FRONT_REPO/frontend:latest
      - name: Build & push backend
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$BACK_REPO/backend:latest ./server
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$BACK_REPO/backend:latest
      - name: Deploy frontend to Cloud Run
        run: |
          gcloud run deploy $FRONTEND_SERVICE \
            --image=$REGION-docker.pkg.dev/$PROJECT_ID/$FRONT_REPO/frontend:latest \
            --region=$REGION \
            --platform=managed \
            --allow-unauthenticated \
            --service-account=${{ vars.WIF_SERVICE_ACCOUNT_EMAIL }}
      - name: Deploy backend to Cloud Run
        run: |
          gcloud run deploy $BACKEND_SERVICE \
            --image=$REGION-docker.pkg.dev/$PROJECT_ID/$BACK_REPO/backend:latest \
            --region=$REGION \
            --platform=managed \
            --allow-unauthenticated \
            --service-account=${{ vars.WIF_SERVICE_ACCOUNT_EMAIL }} \
