on:
  push:
    branches: [ main ] # or dev, etc.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT_EMAIL }}
          
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

      - name: Build & push frontend
        run: |
          docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.FRONT_REPO }}/frontend:latest ./my-app
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.FRONT_REPO }}/frontend:latest

      - name: Build & push backend
        run: |
          docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.BACK_REPO }}/backend:latest ./server
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.BACK_REPO }}/backend:latest

      - name: Deploy frontend to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.FRONTEND_SERVICE }} \
            --image=${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.FRONT_REPO }}/frontend:latest \
            --region=${{ secrets.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --service-account=${{ secrets.WIF_SERVICE_ACCOUNT_EMAIL }}

      - name: Deploy backend to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.BACKEND_SERVICE }} \
            --image=${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.BACK_REPO }}/backend:latest \
            --region=${{ secrets.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --service-account=${{ secrets.WIF_SERVICE_ACCOUNT_EMAIL }}
